# basic_radius_auth
# Autogenerated from man page /usr/local/share/man/man8/basic_radius_auth.8
# using Deroffing man parser
complete -c basic_radius_auth -s f --description 'Specifies the path to a configuration file.'
complete -c basic_radius_auth -s h --description 'Alternative method of specifying the server to connect to .'
complete -c basic_radius_auth -s p --description 'Specify another server port where the RADIUS se… [See Man Page]'
complete -c basic_radius_auth -s i --description 'Unique identifier identifying this Squid proxy … [See Man Page]'
complete -c basic_radius_auth -s w --description 'Alternative method of specifying the shared secret.'

