# basic_ldap_auth
# Autogenerated from man page /usr/local/share/man/man8/basic_ldap_auth.8
# using Deroffing man parser
complete -c basic_ldap_auth -s b --description 'REQUIRED.'
complete -c basic_ldap_auth -s f --description 'LDAP search   filter to locate the user DN.'
complete -c basic_ldap_auth -s u --description 'Specifies the name of the DN attribute that con… [See Man Page]'
complete -c basic_ldap_auth -s U --description 'Use  ldap_compare instead of  ldap_simple_bind … [See Man Page]'
complete -c basic_ldap_auth -s s --description 'Search scope when performing user DN searches s… [See Man Page]'
complete -c basic_ldap_auth -s D -s w --description 'The DN and password to bind as while performing searches.'
complete -c basic_ldap_auth -s W --description 'The DN and the name of a file containing the pa… [See Man Page]'
complete -c basic_ldap_auth -s P --description 'Use a persistent LDAP connection.'
complete -c basic_ldap_auth -s O --description 'Only bind once per LDAP connection.'
complete -c basic_ldap_auth -s R --description 'Do not follow referrals . if !\'po4a\'hide\'.'
complete -c basic_ldap_auth -s a --description 'when to dereference aliases.  Defaults to  never.'
complete -c basic_ldap_auth -s H --description 'Specity the LDAP server to connect to by LDAP U… [See Man Page]'
complete -c basic_ldap_auth -s h --description 'Specify the LDAP server to connect to.'
complete -c basic_ldap_auth -s p --description 'Specify an alternate TCP port where the LDAP se… [See Man Page]'
complete -c basic_ldap_auth -s v --description 'LDAP protocol version.  Defaults to   3 if not specified.'
complete -c basic_ldap_auth -s Z --description 'Use TLS encryption . if !\'po4a\'hide\'.'
complete -c basic_ldap_auth -s S --description 'Enable LDAP over SSL (requires Netscape LDAP API libraries) .'
complete -c basic_ldap_auth -s c --description 'Specify  timeout used when connecting to LDAP s… [See Man Page]'
complete -c basic_ldap_auth -s t --description 'Specify time limit on LDAP search operations . if !\'po4a\'hide\'.'

