# checkmk
# Autogenerated from man page /usr/local/share/man/man1/checkmk.1
# using Deroffing man parser
complete -c checkmk -l ------------------------------------------------ --description '/* A complete test example */.'

