# combine_tessdata
# Autogenerated from man page /usr/local/share/man/man1/combine_tessdata.1
# using Deroffing man parser
complete -c combine_tessdata -s e --description '.'
complete -c combine_tessdata -s o --description '.'
complete -c combine_tessdata -s u --description 'CAVEATS.'

