# exif
# Autogenerated from man page /usr/local/share/man/man1/exif.1
# using Type1
complete -c exif -s v -l version --description 'Display the  exif version number.'
complete -c exif -s i -l ids --description 'Show ID numbers instead of tag names.'
complete -c exif -s t -l tag --description 'Select only this R "TAG" .'
complete -c exif -l ifd --description 'Select a tag or tags from this R "IFD" .'
complete -c exif -s l -l list-tags --description 'List all known EXIF tags and IFDs.'
complete -c exif -l show-mnote --description 'Show the contents of the MakerNote tag.'
complete -c exif -l remove --description 'Remove the tag or (if no tag is specified) the entire IFD.'
complete -c exif -s s -l show-description --description 'Show description of tag.   The --tag option must also be given.'
complete -c exif -s e -l extract-thumbnail --description 'Extract the thumbnail, writing the thumbnail im… [See Man Page]'
complete -c exif -s r -l remove-thumbnail --description 'Remove the thumbnail from the image, writing th… [See Man Page]'
complete -c exif -s n -l insert-thumbnail --description 'Insert  "FILE" as thumbnail.'
complete -c exif -l no-fixup --description 'Do not attempt to fix EXIF specification violat… [See Man Page]'
complete -c exif -s o -l output --description 'Write output image to R "FILE" .'
complete -c exif -l set-value --description 'Set the data for the tag specified with --tag a… [See Man Page]'
complete -c exif -s c -l create-exif --description 'Create EXIF data if it does not exist.'
complete -c exif -s m -l machine-readable --description 'Produce output in a machine-readable (tab-delimited) format.'
complete -c exif -s w -l width --description 'Set the maximum width of the output to N charac… [See Man Page]'
complete -c exif -s x -l xml-output --description 'Produce output in an XML format (when possible).'
complete -c exif -s d -l debug --description 'Show debugging messages.'
complete -c exif -s '?' -l help --description 'Show help message.'

