# ext_time_quota_acl
# Autogenerated from man page /usr/local/share/man/man8/ext_time_quota_acl.8
# using Deroffing man parser
complete -c ext_time_quota_acl -s b --description 'Filename of persistent database.'
complete -c ext_time_quota_acl -s p --description 'Pauselen is given in seconds and defines the pe… [See Man Page]'
complete -c ext_time_quota_acl -s l --description 'Filename where all logging and debugging inform… [See Man Page]'
complete -c ext_time_quota_acl -s d --description 'Enables debug logging in the logfile. if !\'po4a\'hide\'.'
complete -c ext_time_quota_acl -s h --description 'show a short command line help. if !\'po4a\'hide\'.'

