# git-pull
# Autogenerated from man page /usr/local/share/man/man1/git-pull.1
# using Deroffing man parser
complete -c git-pull -l no-progress --description 'Turn progress on/off explicitly.'
complete -c git-pull -o 'e)' --description '.'
complete -c git-pull -s m --description 'option from the command line and want to edit it in the editor.'

