# gnutls-certtool
# Autogenerated from man page /usr/local/share/man/man1/gnutls-certtool.1
# using Type1
complete -c gnutls-certtool -o 'no-inder\\f[]' --description 'Use DER format for input certificates, private … [See Man Page]'
complete -c gnutls-certtool -o 'no-outder\\f[]' --description 'Use DER format for output certificates, private… [See Man Page]'

