# mupdf
# Autogenerated from man page /usr/local/share/man/man1/mupdf.1
# using Deroffing man parser
complete -c mupdf -s p --description 'Uses the given password to open an encrypted PDF file.'
complete -c mupdf -s r --description 'Changes the initial zoom level, specified as th… [See Man Page]'
complete -c mupdf -s b --description 'Changes the anti-aliasing quality, specified as… [See Man Page]'
complete -c mupdf -s C --description 'Sets the full-page tint using hexadecimal color syntax.'

