# mutool
# Autogenerated from man page /usr/local/share/man/man1/mutool.1
# using Deroffing man parser
complete -c mutool -s p --description 'Use the specified password if the file is encrypted.'
complete -c mutool -s g --description 'Garbage collect objects that have no references… [See Man Page]'
complete -c mutool -s d --description 'Decompress streams.'
complete -c mutool -s l --description 'Linearize output.  Create a "Web Optimized" output file.'
complete -c mutool -s i --description 'Toggle decompression of image streams.'
complete -c mutool -s f --description 'Toggle decompression of font streams.'
complete -c mutool -s a --description 'ASCII Hex encode binary streams.'
complete -c mutool -s r --description 'Convert images to RGB when extracting them.'
complete -c mutool -s x --description 'Split the page into this many horizontal pieces.'
complete -c mutool -s y --description 'Split the page into this many vertical pieces.'
complete -c mutool -s b --description 'Print streams as binary data and omit the object header.'
complete -c mutool -s e --description 'Print streams in their original encoded (or compressed) form.'

