# ndisasm
# Autogenerated from man page /usr/local/share/man/man1/ndisasm.1
# using Deroffing man parser
complete -c ndisasm -s v --description 'Causes ndisasm to exit immediately, after displ… [See Man Page]'

