# osinfo-install-script
# Autogenerated from man page /usr/local/share/man/man1/osinfo-install-script.1
# using Type1
complete -c osinfo-install-script -l profile --description 'Choose the installation script profile.'

