# osinfo-query
# Autogenerated from man page /usr/local/share/man/man1/osinfo-query.1
# using Type1
complete -c osinfo-query -s s -l sort-key --description 'Set the data sorting key.  Defaults sorting the first column.'

