# osinfo-detect
# Autogenerated from man page /usr/local/share/man/man1/osinfo-detect.1
# using Type1
complete -c osinfo-detect -l format --description 'Switch between human readable output (plain, th… [See Man Page]'

