# spice-client
# Autogenerated from man page /usr/local/share/man/man1/spice-client.1
# using Type1
complete -c spice-client -l spice-secure-channels --description 'Force the specified channels to be secured .'
complete -c spice-client -l spice-disable-effects --description 'Disable guest display effects .'
complete -c spice-client -l spice-color-depth --description 'Guest display color depth .'
complete -c spice-client -l spice-ca-file --description 'Truststore file for secure connections .'
complete -c spice-client -l spice-host-subject --description 'Subject of the host certificate (field=value pa… [See Man Page]'
complete -c spice-client -l spice-debug --description 'Enable Spice-GTK debugging.'
complete -c spice-client -l spice-disable-audio --description 'Disable audio support.'
complete -c spice-client -l spice-disable-usbredir --description 'Disable \\s-1USB\\s0 redirection support.'
complete -c spice-client -l spice-usbredir-auto-redirect-filter --description 'Filter selecting \\s-1USB\\s0 devices to be auto-… [See Man Page]'
complete -c spice-client -l spice-usbredir-redirect-on-connect --description 'Filter selecting \\s-1USB\\s0 devices to redirect on connect .'
complete -c spice-client -l spice-gtk-version --description 'Display Spice-GTK version information.'
complete -c spice-client -l spice-smartcard --description 'Enable smartcard support.'
complete -c spice-client -l spice-smartcard-db --description 'Path to the local certificate database to use f… [See Man Page]'
complete -c spice-client -l spice-smartcard-certificates --description 'Certificates to use for software smartcards (fi… [See Man Page]'
complete -c spice-client -l spice-cache-size --description 'Image cache size .'

