# tesseract
# Autogenerated from man page /usr/local/share/man/man1/tesseract.1
# using Deroffing man parser
complete -c tesseract -s l --description 'The language to use.  If none is specified, English is assumed.'
complete -c tesseract -o psm --description 'Set Tesseract to only run a subset of layout an… [See Man Page]'
complete -c tesseract -s v --description 'Returns the current version of the tesseract(1) executable.'

