# virt-pki-validate
# Autogenerated from man page /usr/local/share/man/man1/virt-pki-validate.1
# using Type1
complete -c virt-pki-validate -s h -l help --description 'Display command line help usage then exit.'

