# xmlstarlet
# Autogenerated from man page /usr/local/share/man/man1/xmlstarlet.1
# using Deroffing man parser
complete -c xmlstarlet -l version --description 'Display the version of xmlstarlet.'
complete -c xmlstarlet -l help --description 'Display help.'

